### ISSUE TITLE
Can make it work on LispWorks by making do the same as ccl

### ISSUE THREAD

**Issue by Yehouda** [eschulte/graph#7]
I can make it work on LispWorks, i.e. run **(graph/test:test)** without failure, by changing **make-diedge-hash-table**,  **make-edge-hash-table** and **copy-hash** to do on LispWorks the same as they do on CCL. 

BTW: If edges are always two element lists, then you can optimize the hash-function by doing 

`(logxor (sxhash (car edge)) (sxhash (second edge))`

That eliminates the allocation in **copy-tree** and the call to **sort**.

Also consider making an edge a **cons** rather than a **list**, which saved a **cons** object for each edge entry, but that requires more changes.

**Comment by eschulte** [comment]
Thanks for the suggestions.

As it happens we try to support multi-edges (i.e., hyper-graphs), otherwise I would act on your suggestions regarding optimizations for edge representation and hashing.

**Comment by Yehouda** [comment]
Just got around to test it on LispWOrks. 
The fix  is not complete, because it also needs lispworks in the conditionalization in lines  241, 253 and 288 in graph.lisp.
